site_name: Monio
repo_name: 'macbury/monio'
repo_url: 'https://github.com/macbury/monio'

theme:
  font: false
  name: 'material'
  palette:
    primary: 'Red'
    accent: 'Red'

extra:
  disqus: macbury-github-io
  social:
    - link: 'http://macbury.ninja'
      type: 'globe'
    - type: 'github'
      link: 'https://github.com/macbury/monio/'
    - type: 'twitter'
      link: 'https://twitter.com/macbury'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/arkadiusz-buras-83041810/'

copyright: 'Copyright &copy; 2019 Buras Arkadiusz'
site_author: 'Arkadiusz Buras'
site_url: 'https://macbury.github.io/monio'
site_description: 'You personal budget assistant'