source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'dotenv-rails'
gem 'falcon'
gem 'pg', '>= 0.18', '< 2.0'
gem 'rails', '~> 6.0.3.4'
gem 'rails-i18n', '~> 6.0'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'chronic'
gem 'currency-rate'
gem 'devise'
gem 'flipper', '~> 0.17.2'
gem 'flipper-ui', '~> 0.17.2'
gem 'headless'
gem 'icalendar'
gem 'image_processing'
gem 'marcel'
gem 'money-rails'
gem 'rack-cors'
gem 'sentry-raven', require: false
gem 'shrine'

gem 'ar_lazy_preload'

gem 'async'
gem 'async-http', '~> 0.52.4'

gem 'arask'
gem 'axlsx_styler'
gem 'httparty'

gem 'batch-loader'
gem 'graphql', '1.9.18'
gem 'graphql-batch'
gem 'graphql-errors'
gem 'graphql-extras', github: 'macbury/graphql-extras'
gem 'graphql-guard'

gem 'identicon'

gem 'open-location-code'
gem 'search_object'
gem 'search_object_graphql'
# gem 'rumale'
gem 'savon'

gem 'apollo_upload_server', '2.0.0.beta.3'
gem 'classifier-reborn'
gem 'data_migrate'
gem 'down'
gem 'flipper-active_record'
gem 'geokit-rails'
gem 'ice_cube'
gem 'jwt'
gem 'mail'
gem 'pdf-reader', '~> 2.4'
gem 'pg_search'
gem 'rtesseract'
gem 'ruby-msg', github: 'mysociety/ruby-msg'
gem 'terrapin', '~> 0.6.0'

group :production do
  gem 'rack-timeout', '~> 0.6.0'
end

group :development, :test do
  gem 'lol_dba'

  gem 'execution_time'
  gem 'factory_bot_rails'
  gem 'guard'
  gem 'guard-rails', '~> 0.8.1'
  gem 'guard-rake'
  gem 'guard-shell'
  gem 'i18n-tasks'
  gem 'pry', '~> 0.13.1'
  gem 'pry-inline'
  gem 'pry-rails'
  gem 'rails-pg-extras'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', '~> 1.6', '>= 1.6.1'
  gem 'rubocop-rails', '~> 2.6'
  gem 'rubocop-rspec', require: false
  gem 'sprockets', '~> 3' # for handling graphiql rails api explorer view assets
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem 'async-rspec', require: false
  gem 'database_cleaner'
  gem 'faker'
  gem 'shoulda-matchers', require: 'shoulda/matchers'
  gem 'timecop'
  gem 'vcr'
  gem 'rails-controller-testing'
  gem 'webmock'

  gem 'simplecov', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
